server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      # 开启服务发现集成
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 推荐
      routes:
      - id: auth-service-consumer
        uri: lb://auth-consumer
        predicates:
        - Path=/api/auth/login
        - Method=POST
management:
  endpoints:
    web:
      exposure:
        include: health
