server:
  port: 8083
spring:
  application:
    name: auth-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
management:
  endpoints:
    web:
      exposure:
        include: health
